//
//  Ingredient.swift
//  FoudationModelTest
//
//  Created by Piérik Landry on 2026-02-28.
//
import FoundationModels
import Foundation

@Generable(description: "An ingredient with a quantity including a measurement and a name. The id is system-generated and must not be generated by the model.")
struct Ingredient: Sendable, Identifiable {
    
    /// System-generated unique identifier (not generated by the AI)
    var id: UUID { UUID() }
    
    /// Example: "1/4 cup", "2 tbsp", "3 slices"
    @Guide(description: "Enter the quantity of this ingredient such as '1/4 cup' or '2 tbsp'")
    var quantity: String
    
    /// Example: "honey", "pork chops"
    @Guide(description: "The name of the ingredient. Must be capitalized.")
    var name: String
}
