//
//  Recipe.swift
//  FoudationModelTest
//
//  Created by Piérik Landry on 2026-02-28.
//
import FoundationModels
import Foundation

@Generable(description: "A recipe with name, ingredients including measurements, steps, and servings. The id is system-generated and must not be generated by the model.")
struct Recipe: Sendable, Identifiable {
    
    /// System-generated unique identifier (not generated by the AI)
    var id: UUID { UUID() }
    
    var name: String
    var servings: Int
    var nutrition: Nutrition
    var ingredients: [Ingredient]
    var steps: [String]
    @Guide(description: "The kind of recipe. One of: breakfast, lunch, dinner, snack, dessert")
    var kind: Kind
}

